export enum AttendanceRegister {
  ATTENDANCE_REGISTER="ATTENDANCE_REGISTER",
  SECTIONS="SECTIONS",
  GRADES="GRADES",
  PICTURE_PROFILE_URL="PICTURE_PROFILE_URL",
  STUDENT_BY_GRADE_AND_SECTION="STUDENT_BY_GRADE_AND_SECTION",
  SHOW_SIDEBAR="SHOW_SIDEBAR",
  DATA_STUDENT_BY_SEARCH="DATA_STUDENT_BY_SEARCH",
  RESUME_ATTENDANCE_STUDENT="RESUME_ATTENDANCE_STUDENT",
  DATA_STUDENT="DATA_STUDENT"
}