export enum AttendanceRegister {
  ATTENDANCE_REGISTER="ATTENDANCE_REGISTER",
  SECTIONS="SECTIONS",
  GRADES="GRADES",
  PICTURE_PROFILE_URL="PICTURE_PROFILE_URL",
  STUDENT_BY_GRADE_AND_SECTION="STUDENT_BY_GRADE_AND_SECTION"
}